"""empty message

Revision ID: d6fd373db79f
Revises: 
Create Date: 2021-07-29 09:08:19.457505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fd373db79f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_email'), 'rider', ['email'], unique=True)
    op.create_index(op.f('ix_rider_name'), 'rider', ['name'], unique=True)
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('car_number', sa.String(length=5), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_index(op.f('ix_rider_name'), table_name='rider')
    op.drop_index(op.f('ix_rider_email'), table_name='rider')
    op.drop_table('rider')
    # ### end Alembic commands ###
